language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - python -m pip install --upgrade pip
  - python -m pip install -r requirements_test.txt
before_script:
  - export FLASK_APP=unittests/server.py
  - flask run --cert=adhoc &
script:
  - python -m pytest --cov=ga4gh/ --cov-report=term-missing unittests/
after_success:
  - coveralls
after_script:
  - kill %1
